import Head from 'next/head'
import Header from '../Componentes/Header'
import style from '../styles/Home.module.css'

export default function Home() {
    return (
        <section className={style.Container}>
            <Head>
                <title>Harry Potter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={style.headerHome}>
                <Header />
            </section>
            <section className={style.mainHome}>
                <p>Main</p>
            </section>


        </section>
    )
}
