import Head from 'next/head'
// import Footer from '../Componentes/Footer'
import Header from '../Componentes/Header'
import style from '../styles/Home.module.css'

export default function Home() {

    return (
        <section className={style.ContainerHome}>

            <Head>
                <title>Harry Potter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <section className={style.headerHome}> */}
            <Header />
            {/* </section> */}
            <section className={style.mainHome}>
                <div className={style.logos}>
                    <div className={style.logoHarry}>
                        <div className={style.imgLogo} />
                    </div>
                    <div className={style.button}>
                        <button onClick={() => (window.location.href = "/personagens")} className={style.retangulo}>
                            <p>Veja Todos <br />Os Personagens</p>
                        </button>
                    </div>
                </div>
                <div className={style.logoLinha}>
                    <div className={style.imgLogo1}></div>
                    <p className={style.p1}>Navegue pelas Casas</p>
                    <div className={style.imgLinha}></div>
                </div>
            </section>
            <section className={style.footerContainer}>
                <div className={style.imgGrifinoria}></div>
                <div className={style.imgSonserina}></div>
                <div className={style.imgLufaLufa}></div>
                <div className={style.imgCorvinal}></div>
            </section>
        </section>
    )
}
